### ISSUE TITLE
Include baggage processor

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/elastic-otel-java#296]
Include the [baggage processor ](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/baggage-processor)to the agent.

**Comment by SylvainJuge** [comment]
Opened a draft PR to add it to the upstream agent: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11697

Tested locally with a snapshot, the contrib 1.37.0 hasn't been released yet.

If this goes well, then it means that we just have to wait for contrib release, then a new agent release in order to automatically inherit this in our distribution.

**Comment by SylvainJuge** [comment]
[PR ](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11697) has just been merged and will be included in the next upstream agent.

The next step is thus to update to the next upstream agent (likely in early August) and we can close this.
There is no extra configuration change needed as the feature is opt-in by default.

**Comment by SylvainJuge** [comment]
Upstream agent updated in https://github.com/elastic/elastic-otel-java/pull/375 which means we can now use the upstream implementation.
